### ISSUE TITLE
main.css style change

### ISSUE THREAD

**Issue by tcastagna** [thecroux/ecity-leaf#20]
can you change the following css

remove border from menuDrop a
#menuDrop a {
    border-top: none !important;
    color: #fff !important;
}

add the following
#menuDrop li {
    border-top: 1px solid #5d5d5d;
    color: #fff !important;
}

right now there is a top border on the "a tag" in the header menu (for small screens) and i need to move the border to the "LI tag" that holds the "a tag" instead.

**Comment by miguel-perez** [comment]
@tcastagna We pushed up an update, can you verify this is what we wanted?
