### ISSUE TITLE
Update miracleball theme

### ISSUE THREAD

**Issue by miguel-perez** [thecroux/ecity-leaf#27]
From Amber:

>Miracle Ball has some design preferences that they'd like to see on the new site, following some of the elements on the existing site.
>
> I've included a screenshot of the existing home page with some of the design elements tagged. I've also included a screenshot of the new site's home page with corresponding tags. I think my tags are pretty self explanatory, but please let me know if you have any questions at all. 
>
> One detail I'd like to point out is that the style guide currently shows the background (the teal and purple circles) fading out, like it does on the platform. For this one, because the background is so light, can you make it go all the way down? I've noted where it should start and end on the screenshot. 
>
>
> Thanks!
>Amber

![image](https://cloud.githubusercontent.com/assets/1682551/12170732/ae9b6ab6-b511-11e5-9378-83df03633d3e.png)

![image](https://cloud.githubusercontent.com/assets/1682551/12170742/bb59d206-b511-11e5-9e05-751d0f0af11d.png)

**Comment by jdiponziano** [comment]
I think this needs to be updated to miracle ball theme
